export const initialCandidates = [
  { id: 'C-1048', name: 'Lucía Fernández', email: 'lucia.fernandez@email.com', phone: '+54 9 11 4582 9012', role: 'Product Designer', area: 'Diseño', location: 'Buenos Aires', experience: '5 años', salary: '$ 2.400.000', initials: 'LF', color: 'lilac', date: '18 sep 2026', skills: ['Figma', 'UX Research', 'Prototipado'], comments: 'Muy buen perfil. Lideró el rediseño de onboarding en su último equipo y tiene excelentes referencias.', cv: 'CV_Lucia_Fernandez.pdf' },
  { id: 'C-1047', name: 'Mateo González', email: 'mateo.gonzalez@email.com', phone: '+54 9 11 6123 7834', role: 'Frontend Developer', area: 'Tecnología', location: 'Córdoba', experience: '4 años', salary: '$ 3.100.000', initials: 'MG', color: 'peach', date: '18 sep 2026', skills: ['React', 'TypeScript', 'CSS'], comments: 'Referido por el equipo de ingeniería. Disponibilidad inmediata.', cv: 'CV_Mateo_Gonzalez.pdf' },
  { id: 'C-1046', name: 'Sofía Martínez', email: 'sofia.martinez@email.com', phone: '+54 9 11 3201 4467', role: 'People Partner', area: 'Recursos Humanos', location: 'Buenos Aires', experience: '7 años', salary: '$ 2.800.000', initials: 'SM', color: 'mint', date: '17 sep 2026', skills: ['People Ops', 'Cultura', 'HR Analytics'], comments: 'Fuerte experiencia escalando equipos. Coordinar entrevista con dirección.', cv: 'CV_Sofia_Martinez.pdf' },
  { id: 'C-1045', name: 'Tomás Rodríguez', email: 'tomas.rodriguez@email.com', phone: '+54 9 11 7082 1190', role: 'Data Analyst', area: 'Tecnología', location: 'Rosario', experience: '3 años', salary: '$ 2.200.000', initials: 'TR', color: 'blue', date: '16 sep 2026', skills: ['SQL', 'Python', 'Power BI'], comments: 'Perfil analítico sólido. Ya tuvo primera entrevista con el área.', cv: 'CV_Tomas_Rodriguez.pdf' },
  { id: 'C-1044', name: 'Valentina López', email: 'valentina.lopez@email.com', phone: '+54 9 11 5567 2218', role: 'Marketing Manager', area: 'Marketing', location: 'Buenos Aires', experience: '6 años', salary: '$ 2.600.000', initials: 'VL', color: 'pink', date: '15 sep 2026', skills: ['Growth', 'SEO', 'Estrategia'], comments: 'Finalista para la búsqueda de Marketing Lead. Gran fit cultural.', cv: 'CV_Valentina_Lopez.pdf' },
  { id: 'C-1043', name: 'Joaquín Pérez', email: 'joaquin.perez@email.com', phone: '+54 9 11 4256 9810', role: 'Backend Developer', area: 'Tecnología', location: 'Mendoza', experience: '5 años', salary: '$ 3.400.000', initials: 'JP', color: 'yellow', date: '14 sep 2026', skills: ['Node.js', 'PostgreSQL', 'AWS'], comments: '', cv: 'CV_Joaquin_Perez.pdf' },
  { id: 'C-1042', name: 'Camila Torres', email: 'camila.torres@email.com', phone: '+54 9 11 3981 0072', role: 'UX Writer', area: 'Diseño', location: 'Buenos Aires', experience: '3 años', salary: '$ 1.900.000', initials: 'CT', color: 'lavender', date: '12 sep 2026', skills: ['Content Design', 'UX', 'Writing'], comments: 'Se agradeció la participación. Considerar para futuras búsquedas.', cv: 'CV_Camila_Torres.pdf' },
  { id: 'C-1041', name: 'Franco Díaz', email: 'franco.diaz@email.com', phone: '+54 9 11 7712 5843', role: 'Account Executive', area: 'Comercial', location: 'Córdoba', experience: '4 años', salary: '$ 2.100.000', initials: 'FD', color: 'green', date: '10 sep 2026', skills: ['Ventas B2B', 'CRM', 'Negociación'], comments: 'Superó objetivos comerciales por 130% en su último año.', cv: 'CV_Franco_Diaz.pdf' },
]

export const areas = ['Tecnología', 'Diseño', 'Marketing', 'Comercial', 'Recursos Humanos', 'Operaciones']

export const initialSearches = [
  { id: 'B-026', title: 'Senior Frontend Developer', area: 'Tecnología', location: 'Buenos Aires · Híbrido', type: 'Tiempo completo', created: '18 sep 2026', deadline: '15 oct 2026', status: 'Activa', candidates: 12, description: 'Buscamos una persona con experiencia sólida en React y TypeScript para sumarse al equipo de producto.' },
  { id: 'B-025', title: 'Product Designer', area: 'Diseño', location: 'Remoto · Argentina', type: 'Tiempo completo', created: '16 sep 2026', deadline: '10 oct 2026', status: 'Activa', candidates: 8, description: 'Diseñar experiencias simples y accesibles junto a un equipo multidisciplinario.' },
  { id: 'B-024', title: 'People Partner', area: 'Recursos Humanos', location: 'Buenos Aires · Híbrido', type: 'Tiempo completo', created: '12 sep 2026', deadline: '05 oct 2026', status: 'Activa', candidates: 6, description: 'Acompañar el crecimiento de los equipos y desarrollar prácticas de talento.' },
  { id: 'B-023', title: 'Marketing Manager', area: 'Marketing', location: 'Córdoba · Híbrido', type: 'Tiempo completo', created: '02 sep 2026', deadline: '30 sep 2026', status: 'Pausada', candidates: 14, description: 'Liderar la estrategia de adquisición y posicionamiento de marca.' },
  { id: 'B-022', title: 'Data Analyst', area: 'Tecnología', location: 'Remoto · Argentina', type: 'Tiempo completo', created: '28 ago 2026', deadline: '20 sep 2026', status: 'Cerrada', candidates: 19, description: 'Transformar datos en decisiones para los equipos de negocio y producto.' },
]
